# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from apimatic_core.authentication.header_auth import HeaderAuth


class ApiToken(HeaderAuth):

    @property
    def error_message(self):
        """Display error message on occurrence of authentication failure
        in ApiToken

        """
        return "ApiToken: Authorization is undefined."

    def __init__(self, api_token_credentials):
        auth_params = {}
        if api_token_credentials is not None \
                and api_token_credentials.authorization is not None:
            auth_params["Authorization"] = api_token_credentials.authorization
        super().__init__(auth_params=auth_params)


class ApiTokenCredentials:

    @property
    def authorization(self):
        return self._authorization

    def __init__(self, authorization):
        if authorization is None:
            raise ValueError('authorization cannot be None')
        self._authorization = authorization

    def clone_with(self, authorization=None):
        return ApiTokenCredentials(authorization or self.authorization)
