# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from apimatic_core.authentication.header_auth import HeaderAuth


class CsrfToken(HeaderAuth):

    @property
    def error_message(self):
        """Display error message on occurrence of authentication failure
        in CsrfToken

        """
        return "CsrfToken: X-CSRFToken is undefined."

    def __init__(self, csrf_token_credentials):
        auth_params = {}
        if csrf_token_credentials is not None \
                and csrf_token_credentials.x_csrf_token is not None:
            auth_params["X-CSRFToken"] = csrf_token_credentials.x_csrf_token
        super().__init__(auth_params=auth_params)


class CsrfTokenCredentials:

    @property
    def x_csrf_token(self):
        return self._x_csrf_token

    def __init__(self, x_csrf_token):
        if x_csrf_token is None:
            raise ValueError('x_csrf_token cannot be None')
        self._x_csrf_token = x_csrf_token

    def clone_with(self, x_csrf_token=None):
        return CsrfTokenCredentials(x_csrf_token or self.x_csrf_token)
