# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NacRuleMatchingPortTypeEnum(object):

    """Implementation of the 'nac_rule_matching_port_type' enum.

    enum: `wired`, `wireless`

    Attributes:
        WIRED: TODO: type description here.
        WIRELESS: TODO: type description here.

    """
    WIRED = 'wired'

    WIRELESS = 'wireless'

