# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NacPortalTypeEnum(object):

    """Implementation of the 'nac_portal_type_enum' enum.

    TODO: type enum description here.

    Attributes:
        MARVIS_CLIENT: TODO: type description here.
        GUEST: TODO: type description here.

    """
    MARVIS_CLIENT = 'marvis_client'

    GUEST = 'guest'

