# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NacRuleMatchingAuthTypeEnum(object):

    """Implementation of the 'nac_rule_matching_auth_type' enum.

    enum: `cert`, `device-auth`, `eap-teap`, `eap-tls`, `eap-ttls`, `idp`,
    `mab`, `peap-tls`, `psk`

    Attributes:
        CERT: TODO: type description here.
        DEVICEAUTH: TODO: type description here.
        EAPTEAP: TODO: type description here.
        EAPTLS: TODO: type description here.
        EAPTTLS: TODO: type description here.
        IDP: TODO: type description here.
        MAB: TODO: type description here.
        PEAPTLS: TODO: type description here.
        PSK: TODO: type description here.

    """
    CERT = 'cert'

    DEVICEAUTH = 'device-auth'

    EAPTEAP = 'eap-teap'

    EAPTLS = 'eap-tls'

    EAPTTLS = 'eap-ttls'

    IDP = 'idp'

    MAB = 'mab'

    PEAPTLS = 'peap-tls'

    PSK = 'psk'

