# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NacRuleActionEnum(object):

    """Implementation of the 'nac_rule_action' enum.

    enum: `allow`, `block`

    Attributes:
        ALLOW: TODO: type description here.
        BLOCK: TODO: type description here.

    """
    ALLOW = 'allow'

    BLOCK = 'block'

