# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NacTagUsernameAttrEnum(object):

    """Implementation of the 'nac_tag_username_attr_enum' enum.

    TODO: type enum description here.

    Attributes:
        AUTOMATIC: TODO: type description here.
        CN: TODO: type description here.
        UPN: TODO: type description here.
        EMAIL: TODO: type description here.
        DNS: TODO: type description here.

    """
    AUTOMATIC = 'automatic'

    CN = 'cn'

    UPN = 'upn'

    EMAIL = 'email'

    DNS = 'dns'

