# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NacTagTypeEnum(object):

    """Implementation of the 'nac_tag_type' enum.

    enum: `egress_vlan_names`, `gbp_tag`, `match`, `radius_attrs`,
    `radius_group`, `radius_vendor_attrs`, `session_timeout`, `username_attr`,
    `vlan`

    Attributes:
        EGRESS_VLAN_NAMES: TODO: type description here.
        GBP_TAG: TODO: type description here.
        MATCH: TODO: type description here.
        RADIUS_ATTRS: TODO: type description here.
        RADIUS_GROUP: TODO: type description here.
        RADIUS_VENDOR_ATTRS: TODO: type description here.
        SESSION_TIMEOUT: TODO: type description here.
        USERNAME_ATTR: TODO: type description here.
        VLAN: TODO: type description here.

    """
    EGRESS_VLAN_NAMES = 'egress_vlan_names'

    GBP_TAG = 'gbp_tag'

    MATCH = 'match'

    RADIUS_ATTRS = 'radius_attrs'

    RADIUS_GROUP = 'radius_group'

    RADIUS_VENDOR_ATTRS = 'radius_vendor_attrs'

    SESSION_TIMEOUT = 'session_timeout'

    USERNAME_ATTR = 'username_attr'

    VLAN = 'vlan'

