# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NacPortalAccessTypeEnum(object):

    """Implementation of the 'nac_portal_access_type_enum' enum.

    if `type`==`marvis_client`. enum: `wireless`, `wireless+wired`

    Attributes:
        WIRELESS: TODO: type description here.
        ENUM_WIRELESSWIRED: TODO: type description here.

    """
    WIRELESS = 'wireless'

    ENUM_WIRELESSWIRED = 'wireless+wired'

