# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NacPortalTypeEnum1Enum(object):

    """Implementation of the 'nac_portal_type_enum1' enum.

    defines alignment on portal. enum: `center`, `left`, `right`

    Attributes:
        MARVIS_CLIENT: TODO: type description here.
        GUEST: TODO: type description here.

    """
    MARVIS_CLIENT = 'marvis_client'

    GUEST = 'guest'

