# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NacTagMatchEnum(object):

    """Implementation of the 'nac_tag_match' enum.

    if `type`==`match`. enum: `cert_cn`, `cert_issuer`, `cert_san`,
    `cert_serial`, `cert_sub`, `client_mac`, `idp_role`, `mdm_status`,
    `radius_group`, `realm`, `ssid`, `user_name`, `usermac_label`

    Attributes:
        CERT_CN: TODO: type description here.
        CERT_ISSUER: TODO: type description here.
        CERT_SAN: TODO: type description here.
        CERT_SERIAL: TODO: type description here.
        CERT_SUB: TODO: type description here.
        CLIENT_MAC: TODO: type description here.
        IDP_ROLE: TODO: type description here.
        MDM_STATUS: TODO: type description here.
        RADIUS_GROUP: TODO: type description here.
        REALM: TODO: type description here.
        SSID: TODO: type description here.
        USER_NAME: TODO: type description here.
        USERMAC_LABEL: TODO: type description here.

    """
    CERT_CN = 'cert_cn'

    CERT_ISSUER = 'cert_issuer'

    CERT_SAN = 'cert_san'

    CERT_SERIAL = 'cert_serial'

    CERT_SUB = 'cert_sub'

    CLIENT_MAC = 'client_mac'

    IDP_ROLE = 'idp_role'

    MDM_STATUS = 'mdm_status'

    RADIUS_GROUP = 'radius_group'

    REALM = 'realm'

    SSID = 'ssid'

    USER_NAME = 'user_name'

    USERMAC_LABEL = 'usermac_label'

