# -*- coding: utf-8 -*-

"""
mistapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mistapi.api_helper import APIHelper


class ResponseHttp400(object):

    """Implementation of the 'response_http400' model.

    TODO: type model description here.

    Attributes:
        detail (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "detail": 'detail'
    }

    _optionals = [
        'detail',
    ]

    def __init__(self,
                 detail=APIHelper.SKIP):
        """Constructor for the ResponseHttp400 class"""

        # Initialize members of the class
        if detail is not APIHelper.SKIP:
            self.detail = detail 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        detail = dictionary.get("detail") if dictionary.get("detail") else APIHelper.SKIP
        # Return an object of this model
        return cls(detail)
